import {Window} from './runtime/node_modules/happy-dom/lib/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const dashboard=fs.readFileSync(new URL('../../dashboard.html',import.meta.url),'utf8');
const onboarding=fs.readFileSync(new URL('../../onboarding.html',import.meta.url),'utf8');
const w=new Window({url:'https://app.example.test/dashboard.html'});
w.eval(fs.readFileSync(new URL('../../mise-recipe-module.js',import.meta.url),'utf8'));
w.document.body.innerHTML=dashboard.slice(dashboard.indexOf('<div class="page" id="page-recipes">'),dashboard.indexOf('<div class="page" id="page-events">'))+'<button id="wireGoogleReconnect"></button>';
const calls=[],navigation=[],refresh=[],checks=[];let token='first-session-token',delay=null;
const data={success:true,actor:{role:'chef',id:'synthetic-chef'},recipes:[],raw_ingredients:[{ingredient_id:'synthetic-food',name:'Synthetic Food',base_unit:'lb',current_cost_per_unit:null}],batch_components:[],stations:[{code:'saute',label:'Saute'}],units:[{code:'lb',label:'lb'},{code:'portion',label:'portion'}]};
w.MISE_CONFIG={restaurantId:'synthetic-client',apiToken:'synthetic-ai-token',getAccessToken:async()=>token};
for(const name of ['showTab','showWorkspace','showDashboardView','showAudit'])w[name]=(...args)=>{navigation.push({name,args});return true};
w.wireConnect=()=>navigation.push({name:'connect'});w.wireDisconnect=()=>navigation.push({name:'disconnect'});w.wireConnectOpen=()=>navigation.push({name:'connection-dialog'});w.prepLoad=async()=>refresh.push('prep');w.confirm=()=>true;
w.fetch=async(url,opts)=>{calls.push({url,opts,body:opts.body?JSON.parse(opts.body):null});if(delay)await delay;
 if(String(url).includes('miseai-assistant'))return {ok:true,json:async()=>({success:true,reply:'Synthetic guidance only'})};
 if(String(url).includes('scale_pct='))return {ok:true,json:async()=>({success:true,scaled_output_quantity:16,unit:'lb',scaled_inputs:[{name:'<img src=x>',scaled_quantity:20,unit:'lb'}]})};
 return {ok:true,json:async()=>JSON.parse(JSON.stringify(data))};
};
w.eval(fs.readFileSync(new URL('../../mise-recipe-app.js',import.meta.url),'utf8'));
const studio=w.document.getElementById('mise-recipe-studio'),check=async(n,f)=>{await f();checks.push(n);};
await check('Dashboard mounts one permanent Studio and removes the old recipe editor',()=>{assert.ok(studio);assert.equal(w.document.querySelectorAll('mise-recipe-studio').length,1);assert.ok(!dashboard.includes('id="recipe-calculator-script"'));assert.ok(!dashboard.includes('id="rc-form"'));assert.ok(dashboard.includes('src="mise-recipe-app.js"'));});
await check('Onboarding opens the same dashboard recipe workspace with no recipe deadline',()=>{assert.match(onboarding,/href="dashboard.html\?workspace=recipes"/);assert.match(onboarding,/There is no recipe setup deadline/);assert.match(onboarding,/The first 30 days are not billed/);});
await check('Opening Recipes reuses the host restaurant and current user token',async()=>{w.rcShow();assert.equal(await w.miseRecipeConnect(),true);assert.equal(studio.config.restaurantId,'synthetic-client');assert.equal(calls.at(-1).opts.headers.Authorization,'Bearer first-session-token');assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],undefined);});
await check('Repeated visits keep the same element and make no redundant recipe reload',async()=>{const count=calls.length;w.rcShow();await w.miseRecipeConnect();assert.equal(calls.length,count);assert.equal(w.document.getElementById('mise-recipe-studio'),studio);});
await check('Recipe requests obtain a refreshed session token rather than the restaurant AI token',async()=>{token='refreshed-session-token';const h=await studio.headers();assert.equal(h.Authorization,'Bearer refreshed-session-token');assert.ok(!h.Authorization.includes('synthetic-ai-token'));});
await check('Mise AI uses the existing restaurant token and does not issue recipe commands',async()=>{const result=await studio.config.askAI({message:'Synthetic question',history:[],restaurantId:'synthetic-client'});assert.equal(result.reply,'Synthetic guidance only');assert.equal(calls.at(-1).opts.headers.Authorization,'Bearer synthetic-ai-token');assert.equal(calls.at(-1).body.restaurant_id,'synthetic-client');assert.equal(calls.at(-1).body.viewer_role,'chef');assert.equal(calls.filter(c=>c.body?.action).length,0);});
await check('Embedded connection button opens the host connection panel',()=>{studio.shadowRoot.querySelector('#connect').click();assert.equal(navigation.at(-1).name,'connection-dialog');assert.equal(studio.shadowRoot.querySelector('#connection').open,false);});
await check('Normal app navigation preserves editor, tracking draft and CSV queue',()=>{studio.draft.name='Synthetic unsaved';studio.dirty=true;studio.tracking.form={cook:'Synthetic cook'};studio.tracking.dirty=true;const before=studio.draft;w.showWorkspace('inventory','food');w.showDashboardView('monthly');assert.equal(studio.draft,before);assert.equal(studio.tracking.form.cook,'Synthetic cook');assert.ok(studio.hasUnsavedChanges());});
await check('Busy and interrupted confirmations block all app navigation paths',()=>{for(const key of ['busy','uncertain']){studio[key]=true;const n=navigation.length;w.showTab('prep');w.showWorkspace('inventory','food');w.showDashboardView('monthly');w.showAudit();assert.equal(navigation.length,n);studio[key]=false;}studio.tracking.uncertain=true;assert.equal(w.miseRecipeCanNavigate(),false);studio.tracking.uncertain=false;});
await check('Disconnect and reconnect respect unsaved-draft cancellation',()=>{w.confirm=()=>false;const n=navigation.length;w.wireDisconnect();w.wireConnect({preventDefault(){}});assert.equal(navigation.length,n);const event=new w.MouseEvent('click',{bubbles:true,cancelable:true});w.document.getElementById('wireGoogleReconnect').dispatchEvent(event);assert.equal(event.defaultPrevented,true);w.confirm=()=>true;});
await check('Saved recipe and tracking events refresh the existing Prep screen without a second write',async()=>{const n=calls.length;studio.signal('mise-recipe-saved',{prepItemId:'synthetic-item'});studio.signal('mise-tracking-saved',{stockApplied:true});await Promise.resolve();assert.equal(refresh.length,2);assert.equal(calls.length,n);});
studio.dirty=false;studio.tracking.dirty=false;
const headers=['recipe_key','recipe_name','recipe_type','station','yield_quantity','yield_unit','method','ingredient_name','quantity','unit'];
const rows=[['one','Synthetic imported','batch','saute','8','lb','Synthetic method, quoted','Synthetic Food','10','lb']];
await check('Existing Upload Files routes canonical recipe sheets into Step 5 review without saving',async()=>{const count=calls.filter(c=>c.body).length;const r=await w.rcImportParsedRows(headers,rows);assert.equal(r.recipes,1);assert.equal(studio.csv.items[0].meta.method,'Synthetic method, quoted');assert.equal(studio.csv.items[0].lines[0].link.id,'synthetic-food');assert.equal(calls.filter(c=>c.body).length,count);});
await check('Existing legacy recipe-sheet headers are preserved as explicit drafts without guessed quantities',async()=>{const r=await w.rcImportParsedRows(['Recipe Name','Station','Type','Yield Qty','Yield Unit','Ingredient','Amount','Unit','Source','Method'],[['Synthetic legacy','saute','batch','8','lb','Synthetic Food','10','lb','ingredient','Synthetic method']]);assert.equal(r.recipes,1);assert.equal(studio.csv.items[0].meta.recipe_name,'Synthetic legacy');assert.equal(studio.csv.items[0].lines[0].amount,'10');assert.equal(studio.csv.items[0].mode,'');});
await check('Restaurant mismatch rejects AI requests and prevents unsaved cross-restaurant reconnect',async()=>{w.MISE_CONFIG.restaurantId='different-client';await assert.rejects(studio.config.askAI({message:'x',history:[],restaurantId:'synthetic-client'}),/Restaurant changed/);assert.equal(await w.miseRecipeConnect(),false);assert.equal(studio.config.restaurantId,'synthetic-client');w.MISE_CONFIG.restaurantId='synthetic-client';});
await check('Manual chef code remains in memory and is sent only to the kitchen endpoint',async()=>{w.document.getElementById('recipeKitchenCode').value='synthetic-chef-code';assert.equal(await w.miseRecipeConnect(),true);assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],'synthetic-chef-code');assert.equal(calls.at(-1).opts.headers.Authorization,undefined);await studio.config.askAI({message:'x',history:[],restaurantId:'synthetic-client'});assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],undefined);});
await check('Existing saved recipe scale uses the Supabase result and escapes rendered inputs',async()=>{studio.draft.prep_item_id='synthetic-item';studio.dirty=false;w.document.getElementById('recipeAppScale').value='200';w.document.getElementById('recipeAppScaleButton').click();for(let i=0;i<12;i++)await Promise.resolve();const el=w.document.getElementById('recipeAppScaleResult');assert.match(el.textContent,/16 lb/);assert.match(el.textContent,/<img src=x>/);assert.equal(el.querySelector('img'),null);assert.match(calls.at(-1).url,/scale_pct=200/);assert.equal(calls.at(-1).body,null);});
await check('Neither bridge nor Studio persists added credentials',()=>{assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);});
await check('Google-session fallback reads the existing auth client on every request',async()=>{
 const g=new Window({url:'https://app.example.test/dashboard.html?workspace=recipes'});
 g.eval(fs.readFileSync(new URL('../../mise-recipe-module.js',import.meta.url),'utf8'));
 g.document.body.innerHTML='<mise-recipe-studio id="mise-recipe-studio"></mise-recipe-studio><p id="recipeAppStatus"></p>';
 let current='google-session-one',reads=0;
 g.testAuthModule={supabase:{auth:{getSession:async()=>{reads++;return {data:{session:current?{access_token:current}:null},error:null};}}}};
 g.MISE_CONFIG={restaurantId:'synthetic-client',apiToken:'synthetic-ai-token'};
 const visits=[];g.showTab=value=>visits.push(value);g.fetch=async()=>({ok:true,json:async()=>JSON.parse(JSON.stringify(data))});
 const source=fs.readFileSync(new URL('../../mise-recipe-app.js',import.meta.url),'utf8');
 assert.equal(source.split("import('./auth.js')").length,2);
 g.eval(source.replace("import('./auth.js')",'Promise.resolve(window.testAuthModule)'));
 assert.equal(await g.miseRecipeConnect(),true);
 const book=g.document.getElementById('mise-recipe-studio');current='google-session-two';
 assert.equal((await book.headers()).Authorization,'Bearer google-session-two');assert.ok(reads>=2);
 checks.push('Onboarding deep link automatically opens Recipes using existing restaurant access');assert.deepEqual(visits,['recipes']);
 current=null;await assert.rejects(book.headers(),/Reconnect with Google/);
 checks.push('Expired Google session requires reconnection and never substitutes the AI token');
 await g.happyDOM.abort();
});
console.log(JSON.stringify({passed:checks.length,checks},null,2));await w.happyDOM.abort();
