import {Window} from './runtime/node_modules/happy-dom/lib/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const w=new Window({url:'https://app.example.test'});
w.eval(fs.readFileSync(new URL('../../mise-recipe-module.js',import.meta.url),'utf8'));
w.confirm=()=>true;
const el=w.document.createElement('mise-recipe-studio');w.document.body.append(el);
const $=s=>el.shadowRoot.querySelector(s);
const checks=[];
const check=(name,fn)=>{fn();checks.push(name)};
check('Empty recipe renders without credentials',()=>{assert.match(el.shadowRoot.textContent,/Your recipe book starts here/);assert.equal(el.dirty,false)});
const uid='00000000-0000-4000-8000-000000000001',iid='00000000-0000-4000-8000-000000000002',rid='00000000-0000-4000-8000-000000000003';
const calls=[];let recipes=[];let failMode=null;
w.fetch=async(url,opts)=>{
 const b=opts.body?JSON.parse(opts.body):null;calls.push({url,opts,b});
 if(failMode==='network'){failMode=null;throw new Error('Network interrupted')}
 if(failMode==='conflict'){failMode=null;return {ok:false,status:409,json:async()=>({success:false,error:'Recipe changed. Reload before editing.'})}}
 if(url.includes('view=builder'))return {ok:true,json:async()=>({success:true,recipes,raw_ingredients:[{ingredient_id:iid,name:'Potato',base_unit:'oz'}],batch_components:[],stations:[{code:'grill',label:'Grill'}],units:[{code:'oz',label:'oz'},{code:'portion',label:'portion'}]})};
 if(url.endsWith('miseai-assistant'))return {ok:true,json:async()=>({success:true,reply:'Describe how you prepare the potatoes.'})};
 if(b.action==='preview_recipe')return {ok:true,json:async()=>({success:true,cost_complete:false,total_cost:null,cost_per_output:null})};
 const recipe={...(b.payload.recipe||recipes[0].recipe),id:rid,prep_item_id:uid,updated_at:'2026-10-03T22:00:00.000Z',approved_at:b.action==='approve_recipe'?'2026-10-03T22:00:00.000Z':null};
 const prep_item={id:uid,name:b.payload.name||recipes[0].name,station:'grill',unit:'portion'};
 recipes=[{...prep_item,prep_item_id:uid,recipe}];
 return {ok:true,status:200,json:async()=>({success:true,prep_item,recipe})};
};
await el.configure({restaurantId:uid,kitchenCode:'fixture-chef-code',aiApiToken:'fixture-ai-token'});
check('Loads actual builder endpoint with kitchen header',()=>{assert.match(calls.at(-1).url,/prep-kitchen\?view=builder/);assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],'fixture-chef-code')});
$('#name').value='Potato prep';$('#station').value='grill';$('#expected_output_quantity').value='10';el.capture();
$('#add-line').click();$('#add-step').click();
el.draft.recipe.ingredients[0]={stock_kind:'ingredient',name:'Potato',ingredient_id:iid,amount:20,unit:'oz',note:'Diced'};el.draft.recipe.steps=['Wash and dice.'];el.touch();
await el.save();
check('Creates with builder payload and verified success',()=>{assert.equal(calls.at(-1).b.action,'create_recipe');assert.equal(calls.at(-1).b.payload.recipe.ingredients[0].amount,20);assert.equal(el.draft.prep_item_id,uid);assert.equal(el.dirty,false);assert.equal($('#approve').disabled,false)});
await el.approval(true);
check('Approval passes optimistic timestamp',()=>{assert.equal(calls.at(-1).b.action,'approve_recipe');assert.equal(calls.at(-1).b.payload.expected_updated_at,'2026-10-03T22:00:00.000Z');assert.match(el.card(),/Approved for kitchen/)});
$('#notes').value='Keep covered.';el.capture();el.touch();await el.save();
check('Updates same recipe and returns to draft',()=>{assert.equal(calls.at(-1).b.action,'save_recipe');assert.equal(calls.at(-1).b.payload.prep_item_id,uid);assert.equal(el.draft.recipe.approved_at,null);assert.match(el.card(),/Saved draft/)});
$('#notes').value='Keep chilled.';el.capture();el.touch();failMode='conflict';await el.save();
check('Conflict preserves local edits',()=>{assert.equal(el.dirty,true);assert.equal(el.draft.recipe.notes,'Keep chilled.');assert.match($('#status').textContent,/changed elsewhere/)});
failMode='network';await el.save();const retryId=calls.at(-1).b.request_id;assert.equal(el.uncertain,true);assert.equal($('#recipe-form').inert,true);await el.retry();
check('Uncertain save retries reuse request ID',()=>{assert.equal(calls.at(-1).b.request_id,retryId);assert.equal(el.dirty,false)});
await el.calculate();
check('Unknown server costs stay unknown',()=>assert.equal($('#batch-cost').textContent,'—'));
$('#prompt').value='Help with method';await el.ask();
check('AI uses separate restaurant credential and shows reply',()=>{assert.equal(calls.at(-1).opts.headers.Authorization,'Bearer fixture-ai-token');assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],undefined);assert.match($('#chat').textContent,/Describe how/)});
el.draft.name='<img src=x onerror=alert(1)>';el.draft.recipe.steps=['<script>alert(1)</script>'];
check('Printable card escapes user content',()=>{assert.ok(!el.card().includes('<img'));assert.ok(!el.card().includes('<script>'));assert.match(el.card(),/&lt;img/)});
let printed='';Object.defineProperty(w.HTMLIFrameElement.prototype,'srcdoc',{set(value){printed=value},get(){return printed},configurable:true});el.print();
check('Print contains recipe only and page rules',()=>{assert.match(printed,/@page\{size:letter/);assert.ok(!printed.includes('fixture-ai-token'));assert.ok(!printed.includes('Connect your kitchen'))});
el.draft.recipe.ingredients.push({...el.draft.recipe.ingredients[0]});
check('Duplicate ingredients rejected',()=>assert.throws(()=>el.validate(),/duplicate/));el.draft.recipe.ingredients.pop();
const imported={format:'miseai.recipe-card',version:1,restaurant_id:'another-client',payload:{name:'Imported',station:'grill',recipe:{recipe_type:'batch',ingredients:[{ingredient_id:iid,name:'Potato',stock_kind:'ingredient',amount:1,unit:'oz'}],steps:['Prepare'],approved_at:'yesterday'}}};
await el.importJSON(new w.File([JSON.stringify(imported)],'card.json'));
check('Cross-restaurant import strips IDs and approval',()=>{assert.equal(el.draft.recipe.ingredients[0].ingredient_id,undefined);assert.equal(el.draft.recipe.approved_at,null);assert.equal(el.draft.prep_item_id,undefined);assert.equal(el.dirty,true)});
el.dirty=false;await el.configure({restaurantId:'another-client',kitchenCode:'another-code'});
check('Restaurant switch clears old AI credential',()=>assert.equal(el.config.aiApiToken,undefined));
check('No credential persistence',()=>{assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0)});
console.log(JSON.stringify({passed:checks.length,checks},null,2));
await w.happyDOM.abort();
