import {Window} from './runtime/node_modules/happy-dom/lib/index.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const w=new Window({url:'https://app.example.test'});
w.eval(fs.readFileSync(new URL('../../mise-recipe-module.js',import.meta.url),'utf8'));
const el=w.document.createElement('mise-recipe-studio');w.document.body.append(el);
const $=s=>el.shadowRoot.querySelector(s),checks=[],calls=[];
const check=async(name,fn)=>{await fn();checks.push(name);};
const copy=v=>JSON.parse(JSON.stringify(v));w.confirm=()=>true;
const food='food-fixture',main='raw-fixture',batch='batch-fixture';
const recipe=(id,type)=>({prep_item_id:id,name:type==='raw'?'Raw fixture':'Batch fixture',unit:'lb',station:'butcher',recipe:{id:'recipe-'+id,name:id,recipe_type:type,expected_output_quantity:8,expected_output_unit:'lb',expected_input_quantity:10,expected_input_unit:'lb',ingredients:[{stock_kind:'ingredient',ingredient_id:food,name:'Food fixture',amount:10,unit:'lb'}],steps:['Fixture only'],approved_at:'2026-10-03T10:00:00Z',updated_at:'2026-10-03T10:00:00Z'}});
const raw=recipe(main,'raw'),sauce=recipe(batch,'batch');
el.data={recipes:[raw,sauce],raw_ingredients:[],batch_components:[],stations:[{code:'butcher',label:'Butcher'}],units:[{code:'lb',label:'lb'}]};
el.config={restaurantId:'fixture-client',kitchenCode:'fixture-code'};el.connected=true;el.openRecipe(raw);el.setView('raw');
let jobs=[],next=1,fail=null,role='chef',more=false;
const planned=[{stock_kind:'ingredient',stock_id:food,name:'Food fixture',quantity:10,unit:'lb',cost_per_unit:null}];
const results={actual_quantity:8,unit:'lb',raw_usable_yield_pct:90,main_yield_pct:80,total_usable_weight:9,weight_unit:'lb',planned_attainment_pct:100,total_input_cost:null,main_unit_cost:null,waste_cost:null,cost_complete:false,cost_note:'Output cost absorbs input loss.'};
w.fetch=async(url,opts)=>{
 const body=opts.body?JSON.parse(opts.body):null;calls.push({url,opts,body});
 if(fail==='network'){fail=null;throw new Error('Interrupted')}
 if(fail==='conflict'){fail=null;return {ok:false,status:409,json:async()=>({success:false,error:'Job changed',code:'40001'})}}
 if(!body)return {ok:true,json:async()=>({success:true,jobs:copy(jobs),actor:{role},trim_destinations:[{id:'trim-fixture',name:'Retained trim fixture',unit:'lb'}],has_more:more})};
 let j=jobs.find(x=>x.id===body.payload.job_id);
 if(body.action==='preview_tracking')return {ok:true,json:async()=>({success:true,preview:{tracking:{...copy(body.payload.tracking),results:copy(results)},actual_quantity:8,actual_consumption:copy(planned)}})};
 if(body.action==='open_job'){j={id:'job-'+next++,prep_item_id:el.draft.prep_item_id,revision:1,status:'open',target_quantity:Number(body.payload.target_quantity),unit:'lb',opened_at:'2026-10-03T10:00:00.000Z',recipe_snapshot:{name:el.draft.name,recipe:copy(el.draft.recipe)},planned_consumption:copy(planned),tracking:copy(body.payload.tracking)};jobs.unshift(j);}
 else {j.revision++;if(body.payload.tracking)j.tracking=copy(body.payload.tracking);if(body.action==='start_job')j.status='in_progress';if(body.action==='finish_job'){j.status='finished';j.actual_quantity=8;j.actual_consumption=copy(planned);j.tracking.results=copy(results);j.finished_at='2026-10-03T12:00:00Z';j.finished_by={role:'chef',id:'fixture-actor'};}}
 return {ok:true,json:async()=>({success:true,job:copy(j),stock_applied:body.action==='finish_job'})};
};
const set=(key,value)=>{const input=$('[data-track="'+key+'"]');assert.ok(input,key);input.value=value;input.dispatchEvent(new w.Event('input',{bubbles:true}));};
await check('Raw view opens with empty actuals and no backend request',()=>{assert.equal(calls.length,0);assert.equal($('[data-track-action="open"]').disabled,true);assert.equal($('[data-track="cook"]').value,'');assert.match($('#view-panel-raw').textContent,/Main output excludes retained trim/);});
await el.loadTracking();
await check('Tracking read reuses restaurant access and loads approved trim options',()=>{assert.match(calls.at(-1).url,/view=tracking/);assert.match(calls.at(-1).url,/prep_item_id=raw-fixture/);assert.equal(calls.at(-1).opts.headers['x-kitchen-code'],'fixture-code');assert.equal($('[data-track-action="open"]').disabled,false);assert.match($('#view-panel-raw').textContent,/Retained trim fixture/);});
set('target_quantity','8');set('cook','Fixture cook');set('prep_date','2026-10-03');set('trim_stock_id','trim-fixture');set('trim_allocation','proportional');await el.saveTracking('open');
await check('Chef opens a planned run with explicit quantity and trim allocation',()=>{assert.equal(calls.at(-1).body.action,'open_job');assert.equal(calls.at(-1).body.payload.tracking.kind,'raw');assert.equal(calls.at(-1).body.payload.tracking.trim_allocation,'proportional');assert.equal(el.trackingJob().status,'open');assert.equal(el.tracking.dirty,false);assert.equal($('[data-consumed="0"]').value,'');});
set('weight_in','10');set('main_output','8');set('retained_trim','1');set('discarded','1');
await check('Actual consumption remains blank until the chef enters or deliberately copies it',()=>{assert.equal(el.trackingPayload().actual_consumption[0].quantity,null);$('[data-track-action="planned"]').click();assert.equal($('[data-consumed="0"]').value,'10');assert.equal(el.tracking.dirty,true);});
await el.saveTracking('save');
await check('Partial entries save through existing job update and revision checks',()=>{assert.equal(calls.at(-1).body.action,'update_job');assert.equal(calls.at(-1).body.payload.expected_revision,1);assert.equal(el.trackingJob().revision,2);assert.equal(el.tracking.form.weight_in,'10');assert.equal(el.tracking.dirty,false);assert.equal(el.trackingJob().status,'open');});
await el.saveTracking('start');
await check('Starting keeps entries and requires existing job revision',()=>{assert.equal(calls.at(-1).body.action,'start_job');assert.equal(calls.at(-1).body.payload.expected_revision,2);assert.equal(el.trackingJob().status,'in_progress');assert.equal(el.tracking.form.main_output,'8');assert.equal($('[data-track-action="finish"]').disabled,true);});
await check('Run form and payload retain snapshot type if the current recipe type changes',()=>{el.draft.recipe.recipe_type='batch';assert.equal(el.trackingKind(),'raw');assert.equal(el.trackingPayload().tracking.kind,'raw');el.draft.recipe.recipe_type='raw';});
await el.calculateTracking();
await check('Supabase result displays raw yields and visibly unknown costs',()=>{assert.equal(calls.at(-1).body.action,'preview_tracking');assert.match($('#tracking-calculation').textContent,/90%/);assert.match($('#tracking-calculation').textContent,/costs are unknown/);assert.equal($('[data-track-action="finish"]').disabled,false);assert.equal(el.tracking.preview.tracking.results.waste_cost,null);});
set('main_output','7');
await check('Any actual edit invalidates review and hides stale calculation',()=>{assert.equal(el.tracking.preview,null);assert.equal($('#tracking-calculation').hidden,true);assert.equal($('[data-track-action="finish"]').disabled,true);});
set('main_output','8');await el.calculateTracking();
await check('Cancelled completion does not send a stock request',async()=>{const n=calls.length;w.confirm=()=>false;await el.saveTracking('finish');assert.equal(calls.length,n);w.confirm=()=>true;});
await el.saveTracking('finish');
await check('Completed card displays immutable actual inputs, snapshot and completion actor',()=>{assert.equal(calls.at(-1).body.action,'finish_job');assert.equal(el.trackingJob().status,'finished');assert.equal($('#tracking-form'),null);assert.match($('#view-panel-raw').textContent,/Actual ingredients consumed/);assert.match($('#view-panel-raw').textContent,/fixture-actor/);assert.match($('#view-panel-raw').textContent,/recipe-raw-fixture/);assert.equal($('[data-track-action="finish"]'),null);});
await check('Saved tracking print contains actual entries and no credentials or app interface',()=>{const html=el.trackingPaper();assert.match(html,/Saved completed results/);assert.match(html,/10 lb/);assert.match(html,/job-1/);assert.ok(!html.includes('fixture-code'));assert.ok(!html.includes('Ask Mise AI'));});
await check('Blank raw worksheet has writing blanks and frozen standard quantities',()=>{const html=el.trackingPaper(true);assert.match(html,/RAW YIELD WORKSHEET/);assert.match(html,/____________/);assert.match(html,/Main usable output · excludes retained trim/);assert.match(html,/10 lb/);assert.ok(!html.includes('Saved actual results'));});
let printed='';Object.defineProperty(w.HTMLIFrameElement.prototype,'srcdoc',{set(v){printed=v},get(){return printed},configurable:true});el.printTracking(true);
await check('Tracking print isolates chosen card and repeats table headers with letter margins',()=>{assert.match(printed,/RAW YIELD WORKSHEET/);assert.match(printed,/@page\{size:letter/);assert.match(printed,/thead\{display:table-header-group/);assert.ok(!printed.includes('Recipe book'));});
el.selectTracking(null);set('target_quantity','8');set('cook','Fixture cook');set('prep_date','2026-10-03');fail='network';await el.saveTracking('open');const retryId=calls.at(-1).body.request_id;
await check('Interrupted tracking request locks navigation, recipe editing and run fields',()=>{assert.equal(el.tracking.uncertain,true);assert.equal($('#recipe-form').inert,true);assert.equal($('#tracking-form').inert,true);assert.equal(el.setView('recipe'),false);assert.equal(el.canLeave(),false);assert.equal($('[data-track-action="load"]').disabled,true);});
await el.retryTracking();
await check('Tracking retry uses the exact same request ID and payload',()=>{assert.equal(calls.at(-1).body.request_id,retryId);assert.deepEqual(calls.at(-1).body.payload,calls.at(-2).body.payload);assert.equal(el.tracking.uncertain,false);assert.equal(el.tracking.selected,'job-2');});
set('cook','Local unsaved');fail='conflict';await el.saveTracking('save');
await check('Concurrent revision conflict preserves local tracking entries',()=>{assert.equal(el.tracking.form.cook,'Local unsaved');assert.equal(el.tracking.dirty,true);assert.match($('#status').textContent,/entries are preserved/);});
await check('Browser exit and restaurant changes protect tracking drafts',async()=>{const e=new w.Event('beforeunload',{cancelable:true});w.dispatchEvent(e);assert.equal(e.defaultPrevented,true);await assert.rejects(el.configure({restaurantId:'other-client'}),/Save or export/);});
await check('Linked component visit preserves parent tracking draft',()=>{el.draft.recipe.ingredients.push({stock_kind:'prep',prep_item_id:batch,name:'Batch fixture',amount:1,unit:'lb'});el.render();assert.equal(el.openComponent(1),true);assert.equal(el.hasUnsavedChanges(),true);assert.equal(el.returnToParent(),true);assert.equal(el.tracking.form.cook,'Local unsaved');assert.equal(el.tracking.dirty,true);});
await check('Cook role cannot change trim allocation in the form',()=>{el.tracking.role='cook';el.renderTracking();assert.equal($('[data-track="trim_stock_id"]').disabled,true);assert.equal($('[data-track="trim_allocation"]').disabled,true);});
await check('Recipe confirmation interruption also freezes tracking operations',async()=>{el.uncertain=true;el.refreshButtons();const n=calls.length;assert.equal($('[data-track-action="save"]').disabled,true);await el.saveTracking('save');await el.loadTracking();assert.equal(calls.length,n);el.uncertain=false;el.refreshButtons();});
el.tracking.dirty=false;el.openRecipe(sauce);el.setView('batch');jobs=[];role='chef';await el.loadTracking();set('target_quantity','8');set('cook','Fixture cook');set('prep_date','2026-10-03');await el.saveTracking('open');
await check('Batch form separates actual output, discarded product and raw weights',()=>{assert.ok($('[data-track="actual_quantity"]'));assert.ok($('[data-track="discarded"]'));assert.equal($('[data-track="weight_in"]'),null);assert.match($('#view-panel-batch').textContent,/moisture loss/);assert.match(el.trackingPaper(true),/BATCH TRACKING WORKSHEET/);});
await check('Batch blank actuals stay null and do not default to planned amounts',()=>{const p=el.trackingPayload();assert.equal(p.actual_quantity,null);assert.equal(p.tracking.discarded,null);assert.equal(p.actual_consumption[0].quantity,null);});
await check('Unsafe tracking content is escaped in screen and print cards',()=>{el.tracking.form.cook='<script>bad</script>';el.tracking.form.prep_date='<img src=x>';const h=el.trackingCard()+el.trackingPaper();assert.ok(!h.includes('<script>'));assert.ok(!h.includes('<img'));assert.match(h,/&lt;script/);});
await check('Incomplete save confirmation keeps the exact request pending and blocks departure',async()=>{const original=el.request;el.request=async()=>({success:true,job:{id:'incomplete-job'}});await assert.rejects(el.trackingCommand('update_job',el.trackingPayload()),/confirmation was interrupted/);assert.equal(el.tracking.uncertain,true);assert.ok(el.tracking.pending.id);assert.equal(el.canLeave(),false);el.request=original;});
await check('Tracking does not persist access credentials',()=>{assert.equal(w.localStorage.length,0);assert.equal(w.sessionStorage.length,0);});
console.log(JSON.stringify({passed:checks.length,checks},null,2));await w.happyDOM.abort();
